// Configurazione dell'applicazione

APP_VERSION = 1.12
TOTEM_API_KEY=api_key_totem_1
BASE_URL=http://localhost:8080/api/v1/totem/

MAX_OFFLINE_DAYS = 30


DEBUG_SIMULATE_UPDATE = false
DEBUG_SIMULATE_OFFLINE = false

INTERVAL_ONLINE_MS = 10000
INTERVAL_OFFLINE_MS = 3000
PING_TIMEOUT_MS = 6000
